version: '3'
services:
  cennznet:
    name: cennznet-validator-sidecar
    image: cennznet/cennznet:2.0.0-rc5
    volumes:
    - ./data/cennznet:/mnt/data
    command:
      - --dev
      - --validator
      - --base-path=/mnt/data
      - --name=cennznet-${HOSTNAME}
      - --unsafe-ws-external
      - --unsafe-rpc-external
      - --rpc-cors=all
    ports:
      - "9933:9933"
      - "9944:9944"
  mongo:
    name: mongodb-sidecar
    image: mongo/mongo:5
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME="${MONGO_INITDB_ROOT_USERNAME}"
    - MONGO_INITDB_ROOT_PASSWORD="${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
