version: '3'
services:
#  cennznet:
#    image: cennznet/cennznet:2.0.0-rc5
#    volumes:
#    - ./data/cennznet:/mnt/data
#    command:
#      - --dev
#      - --base-path=/mnt/data
#      - --name=cennznet-${HOSTNAME}
#      - --unsafe-ws-external
#      - --unsafe-rpc-external
#      - --rpc-cors=all
#    ports:
#      - "9933:9933"
#      - "9944:9944"
  mongo:
    image: mongo:5
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
